feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
delta_time: 0.0

common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/handsfree/imu"

preprocess:
    lidar_type: 2 # 1:Livox Avia LiDAR  2:VELO16  3:OUST64  4:XT32 
    scan_line: 32 # 16  64  32
    blind: 5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    # lidar->imu?
    extrinsic_T: [ 0.29, 0.0, 0.17 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

pcd_save:
    pcd_save_en: false

camera:
# camera -> imu ?
    img_topic: /camera/color/image_raw
    Rcl: [0.0, 0.0, 1.0,
         -1.0, 0.0, 0.0,
          0.0, -1.0,0.0]
    Pcl: [0.57711, 0.0, 0.83333]
    
